Repository helm/chart-releaser, pull requests merged in 2019-03, with the labels that each got.

#26 Polish readme
  README.md
Labels: size/S

#25 Update README doc
  README.md
Labels: size/XS

#29 Upgrade to Go 1.12 and switch to modules
  .circleci/config.yml
  Gopkg.lock
  Gopkg.toml
  README.md
  go.mod
  go.sum
Labels: size/XL
