Repository helm/chart-releaser, pull requests merged in 2019-02, with the labels that each got.

#15 Ensure correct licensing
  LICENSE
  main.go
  pkg/github/github.go
  pkg/index/main.go
  pkg/upload/main.go
Labels: size/L

#17 Change tag pattern to bypass semver precedence issue
  pkg/upload/main.go
Labels: size/XS

#20 dep ensure must be run from within a known GOPATH/src
  .goreleaser.yml
Labels: size/XS

#21 Remove goreleaser variable expansion
  .goreleaser.yml
Labels: size/XS

#22 Move gorelaser before hook to circle job
  .circleci/config.yml
  .goreleaser.yml
Labels: size/S

#24 re: Fix tag pattern for index command
  pkg/index/main.go
Labels: size/S
