Repository helm/chart-releaser, pull requests merged in 2020-03, with the labels that each got.

#53 Updating config.yaml README example to match changes in PR#37
  README.md
Labels: size/XS

#58 Update readme
  README.md
Labels: size/M

#60 Bump Alpine to 3.11
  Dockerfile
Labels: size/XS

#59 Update Go version, dependencies, and GoReleaser
  .circleci/config.yml
  .goreleaser.yml
  build.sh
  go.mod
  go.sum
  pkg/github/github.go
  pkg/tools/tools.go
  setup.sh
Labels: size/XL

#61 Add Homebrew formula
  .goreleaser.yml
  README.md
Labels: size/S
