Repository helm/chart-releaser, pull requests merged in 2020-09, with the labels that each got.

#76 chore: Update base-image
  Dockerfile
Labels: size/XS

#75 Migrate to GitHub Actions
  .circleci/config.yml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  LICENSE
  build.sh
  cr/cmd/index.go
  cr/cmd/package.go
  cr/cmd/root.go
  cr/cmd/upload.go
  cr/cmd/version.go
  cr/main.go
  go.mod
  go.sum
  magefile.go
  pkg/config/config.go
  pkg/git/git.go
  pkg/github/github.go
  pkg/packager/packager.go
  pkg/packager/packager_test.go
  pkg/releaser/releaser.go
  pkg/releaser/releaser_test.go
  pkg/tools/tools.go
  setup.sh
  tag.sh
Labels: size/XL

#77 Update build badge for GitHub workflow
  README.md
Labels: size/XS

#78 Fix release workflow
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
Labels: size/M
