Repository helm/chart-releaser, pull requests merged in 2021-02, with the labels that each got.

#99 Update releaser to regenerate generated field on index update
  pkg/releaser/index979928834/index.yaml
  pkg/releaser/releaser.go
  pkg/releaser/releaser_test.go
  pkg/releaser/testdata/empty-repo/index.yaml
Labels: size/M

#104 Add missing tool dependencies to tools.go
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  go.mod
  go.sum
  pkg/packager/packager.go
  pkg/tools/tools.go
Labels: size/L

#105 Update dependencies
  .goreleaser.yml
  go.mod
  go.sum
  pkg/github/github.go
  pkg/releaser/releaser.go
Labels: size/XL

#106 Add missing Docker login step
  .github/workflows/release.yaml
Labels: size/XS

#108 Fix .goreleaser.yml for the homebrew tap formula
  .goreleaser.yml
Labels: size/XS
