Repository helm/chart-releaser, pull requests merged in 2021-11, with the labels that each got.

#140 Some dependencies / tools updates
  Dockerfile
  go.mod
  go.sum
Labels: size/XXL

#144 Deprecate cr index "charts-repo" flag. Instead read index.yaml from git repository
  README.md
  cr/cmd/index.go
  pkg/releaser/releaser.go
  pkg/releaser/releaser_test.go
Labels: size/L

#147 fix typo in README
  README.md
Labels: size/XS
