Repository helm/chart-releaser, pull requests merged in 2021-03, with the labels that each got.

#111 Adding option to skip existing releases
  cr/cmd/upload.go
  pkg/config/config.go
  pkg/releaser/releaser.go
Labels: enhancement, size/XS

#110 Open release file in retry loop
  pkg/github/github.go
Labels: size/S

#113 Docker entrypoint ...
  Dockerfile
Labels: size/XS

#116 bug: add git to docker image to run cr index
  Dockerfile
Labels: size/XS
