Repository helm/chart-releaser, pull requests merged in 2022-03, with the labels that each got.

#151 add pages-index-path option
  README.md
  cr/cmd/index.go
  pkg/config/config.go
  pkg/releaser/releaser.go
  pkg/releaser/releaser_test.go
Labels: size/M

#154 update helm dependencie to use 3.8.1 release
  go.mod
  go.sum
Labels: size/XS

#153 add dependabot config
  .github/dependabot.yml
Labels: size/S

#166 add missing environment to be able to sign using keyless approach
  .goreleaser.yml
Labels: size/XS

#167 fix docker build
  .goreleaser.yml
Labels: size/M

#168 fix double tag in the manifest
  .goreleaser.yml
Labels: size/S
