Repository helm/chart-releaser, pull requests merged in 2023-01, with the labels that each got.

#239 update go-github dependency to v49
  go.mod
  go.sum
  pkg/github/github.go
Labels: size/XS

#240 CI cleanup, base image bump
  .github/dependabot.yml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .goreleaser.yml
  Dockerfile
  build.sh
  magefile.go
Labels: size/L

#229 accept generate_release_notes in github api upload to automatically g…
  README.md
  cr/cmd/upload.go
  doc/cr_upload.md
  pkg/config/config.go
  pkg/github/github.go
  pkg/releaser/releaser.go
Labels: size/M
