Repository helm/chart-releaser, pull requests merged in 2024-06, with the labels that each got.

#424 Updates on ci/goreleaser
  .github/auto-merge-deps.yml
  .github/dependabot.yml
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .goreleaser.yml
  cr/cmd/index.go
  cr/cmd/upload.go
  cr/cmd/version.go
  go.mod
  go.sum
Labels: size/XL

#420 TIDY unused packages-with-index HTTPClient
  pkg/releaser/releaser.go
Labels: size/S

#426 DOCS fix commit-ish typo
  pkg/git/git.go
  pkg/releaser/releaser.go
Labels: size/XS
